services:
  - type: web
    name: bg-remover-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    region: oregon
    plan: free
    branch: main
    runtime: python
